---
-
  hosts: all
  gather_facts: true # this will make not to gather facts before running tasks

  vars: 
   services:
        - { name: 'Bits', status: 'stopped' }
        - { name: 'windowupdate', status: 'started' }
        - { name: 'dnscache', status: 'started' }

  tasks:
   - name: Stop all services
     win_service:
       name: "{{ item.name }}"
       state: "{{ item.status }}"
     loop: "{{services}}"
     tags: ansibleloop

# you can use below msg if any of the value not found or not assigned
# The port used for the {{ansible_os_family | default('windows') }}


             

...
